---
  - hosts: all  # yamllint disable-line rule:indentation
    become: true

    pre_tasks:
      - name: Update APT cache
        apt: update_cache=yes

    roles:
      - role: azavea.buildkite-agent
